### ISSUE TITLE
Update AssetType for NEP5

### ISSUE THREAD

**Issue by Chubby-Chocobo** [neo-project/docs#256]
I see in [main net assets list](https://neotracker.io/browse/asset/1) there some assets with type `NEP5` like APH and RPX.
I'm confuse which one is it in [this document](https://github.com/neo-project/docs/blob/master/en-us/sc/fw/dotnet/neo/Asset/AssetType.md)?

One more thing is there's no NEP5 asset in [testnet](https://testnet.neotracker.io/browse/asset/1). I actually try deploy and invoke a test token base on ICO_Template project but it didn't appear. Is NEP5 not supported on testnet or something?
Thanks,

**Comment by PeterLinX** [comment]
@Chubby-Chocobo  NEO has two kinds of assets. One is global asset, like NEO, GAS and so on. The other asset is contract asset. 
Answer:
1. The docs you're checking is about global asset. However, APH or RPX is contract asset.
2. Testnet support nep5 of course. You can't find them on blockchain browser just because browser choose not to support them. You can contact the author of that browser. You can find your nep5 asset in neo testnet by using rpc [api](http://docs.neo.org/zh-cn/node/api/getcontractstate.html).

**Comment by Chubby-Chocobo** [comment]
@PeterLinX Thank you, I got the difference between global asset and contract asset.
The browser I use for both networks is `neotracker.io`. The NEP5 assets are still listed in the [mainnet](https://neotracker.io/browse/asset/1), but not in the [testnet](https://testnet.neotracker.io/browse/asset/1).
Do you know how can I get contact with guys in neotracker?
Many thanks,

**Comment by PeterLinX** [comment]
You can contact him in his [github](https://github.com/neotracker).
