### ISSUE TITLE
Heights are stuck at 0/0/0 after Start Consensus. Cannot successfully get 100M Neo to account after broadcasting

### ISSUE THREAD

**Issue by iamn3rdz** [neo-project/docs#351]
![image](https://user-images.githubusercontent.com/29269949/35199155-937db1d4-feb7-11e7-99a2-29f7269e4782.png)

I have been following the instructions from http://docs.neo.org/en-us/node/private-chain.html and cannot seem to actually get the 100M transferred to the wallet. I am stuck on step 4 or 5.

**Comment by iamn3rdz** [comment]
![image](https://user-images.githubusercontent.com/29269949/35199175-c961e55e-feb7-11e7-8536-483e2786940f.png)

**Comment by jonatanblockchain** [comment]
Looks like your not generating/validating blocks (height on consensus nodes are not changing)
Try:
1- Stop consensus node
2- Delete peer.dat and Chain folder on consensus nodes
3- Delete peer.dat and Chain folder on neo-gui 
4- Start consensus node

**Comment by iamn3rdz** [comment]
Hey jonatanblockchain. Thanks for the respons, I've seen you have already responded to a few posts like mine. I've done as you suggested with no success unfortunately. is this the correct place to find the virutal machines IP adress? I'm using HyperV 
![image](https://user-images.githubusercontent.com/29269949/35227733-0d37e3b6-ff4c-11e7-9e14-fd43b8791f24.png)

I have also opened up the ports in the firewall with no success.

**Comment by NeoParticle** [comment]
Hi, you might have downloaded the release version which has some bug. Build Neo-Cli from source code where the issue has been resolved. I got frustrated because of this issue for nearly 2 days, later realized the issue was on the release version. And also I found the release version has been updated 9 days ago. So try download a fresh copy of the release version 2.6.0
