### ISSUE TITLE
docs on "invoke" RPC endpoint are missing

### ISSUE THREAD

**Issue by devhawk** [neo-project/docs#968]
invokefunction and invokescript are present, but invoke is missing

**Comment by corollari** [comment]
I think invoke was deprecated as it had some problems, that's probably the reason it's not in the docs.

**Comment by devhawk** [comment]
its still in the master 2.x branch. If we are deprecating the endpoint, there should be docs detailing that fact

**Comment by corollari** [comment]
Well there's already docs on that:
["Please use the alternative method invokefunction instead. invoke will be deprecated in NEO3."](https://github.com/neo-project/docs/blob/master/faq/en-us/client.md)

Overall there's no need to use invoke given that invokefunction can be used for the same purposes and invoke gives some wrong results (see the FAQ question linked above). I imagine invoke was left in the implementation for backwards compatibility but it was not included in the docs to prevent people using it instead of `invokefunction`, which would probably lead to wasted time spent on debugging.

But feel free to send a PR adding it to the docs :smile:.
